### Absa Login
# @name login_pin
POST https://vs1.absa.co.za/absa-online/j_pin_security_login HTTP/1.1
Accept: */*
Content-Type: application/x-www-form-urlencoded

AccessAccount=4104754941&PIN=19910&Operator=1&CaptchaTxt=

@cookie = {{{{login_pin.response.headers.Set-Cookie}}}}

### Proxy
POST https://ib.absa.co.za/absa-online/proxy HTTP/1.1


